[frontend]
frontend_server ansible_host=13.218.16.75 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/open-invite-key

[backend]
backend_server ansible_host=13.221.121.104 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/open-invite-key

[jenkins]
jenkins_server ansible_host=34.235.131.47 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/open-invite-key

[all:vars]
database_host=open-invite-staging-db.c07umimsy4fb.us-east-1.rds.amazonaws.com
database_port=5432
database_name=openinvite
database_user=dbadmin
database_password=OpenInvite2024!Secure
